services:
  api:
    image: ghcr.io/${GITHUB_ACTOR}/auto-verdict-api:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  processing-service:
    image: ghcr.io/${GITHUB_ACTOR}/auto-verdict-processing-service:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  frontend:
    image: ghcr.io/${GITHUB_ACTOR}/auto-verdict-frontend:${IMAGE_TAG}
    restart: unless-stopped

  prerender:
    image: ghcr.io/${GITHUB_ACTOR}/auto-verdict-prerender:${IMAGE_TAG}
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  nats:
    restart: unless-stopped

  seaweedfs:
    restart: unless-stopped

  grafana:
    restart: unless-stopped
