using System.Text;
using AutoVerdict.Application.Storage;
using AutoVerdict.Contracts.Messages;

namespace AutoVerdict.ProcessingService.Pipeline;

/// <summary>
/// Drop-in replacement for <see cref="CarCheckAnalysisPipeline"/> used when
/// <c>Processing:TestMode = true</c>. Waits a random 5–20 s to simulate real
/// pipeline latency, then saves a static pre-prepared report to storage.
/// No external services (Claude, Playwright, storage crawl) are contacted.
/// </summary>
public sealed class FakeCarCheckPipeline(
    IDocumentStorageClient storage,
    ILogger<FakeCarCheckPipeline> logger) : ICarCheckPipeline
{
    private const string AnalysisFileName = "ai-analysis-result.md";

    private static readonly Random Rng = Random.Shared;

    private const string FakeReport =
        """
        # 🟠 Buy with caution — 2021 Toyota Corolla 1.8 Hybrid

        Overall, this vehicle is in reasonable condition for its age and mileage. A few items warrant
        closer inspection before committing to a purchase, particularly around service history
        completeness and minor bodywork on the rear quarter.

        ## At a glance

        | Attribute | Detail |
        |-----------|--------|
        | Make / Model | Toyota Corolla 1.8 Hybrid (E210) |
        | Year | 2021 |
        | Mileage | 74,000 km |
        | Asking price | ~89,900 PLN |
        | Fuel | Hybrid (petrol + electric) |
        | Transmission | CVT (e-CVT) |
        | Body | Sedan |

        > ⚠ **TEST MODE** — This report was generated by the local fake pipeline.
        > No AI or external services were used. The content below is static and does not
        > reflect a real vehicle analysis.

        ---

        ## Risk factors

        ### 🔴 High priority

        - **Service history gap (2022–2023)**: The provided description mentions two years without
          documented servicing. Toyota hybrids require annual inspection of the hybrid battery cooling
          system; missing this can shorten battery life significantly. Request full dealer printout
          before purchase.
        - **Hybrid battery health unknown**: No battery health report was provided. Request a hybrid
          system health check (available at any Toyota dealer for ~200 PLN) before signing.

        ### 🟠 Medium priority

        - **Rear quarter repaint**: Photos show a slight colour mismatch on the left rear quarter,
          suggesting a prior impact or repaint. Have an independent bodywork specialist inspect for
          hidden structural damage.
        - **Tyre wear uneven**: Inner edges on the front axle appear more worn than the outer edges,
          hinting at possible wheel alignment issues. Budget 150–300 PLN for a 4-wheel alignment.
        - **Price slightly above market**: Current market average for comparable 2021 Corolla Hybrid
          sedans in Poland is ~86,000–88,000 PLN. The asking price of 89,900 PLN leaves limited
          negotiation room but is not unreasonable given the low mileage.

        ### 🟢 Low priority

        - Interior in good condition; no visible smoke damage or excessive wear on the driver's seat.
        - All four tyres are the same brand (Michelin Primacy 4), which is a positive sign.
        - Factory navigation and safety suite (Toyota Safety Sense) confirmed in photos.

        ---

        ## Pre-purchase checklist

        - [ ] Request full Toyota dealer service history printout
        - [ ] Commission hybrid battery health report (Toyota dealer or certified hybrid specialist)
        - [ ] Independent bodywork inspection — focus on left rear quarter
        - [ ] VIN history check (autorai.pl, historiapojazdu.gov.pl, or CarVertical)
        - [ ] 4-wheel alignment check
        - [ ] Test drive ≥ 30 km, including at least 15 min on a motorway at 110–130 km/h
        - [ ] Verify all Toyota Safety Sense features work (adaptive cruise, lane assist)
        - [ ] Check all charging ports and hybrid readouts on the dashboard

        ---

        ## Questions to ask the seller

        1. Why is the car being sold, and is there a second key?
        2. Can you provide the full service history, including dealer stamps?
        3. Was the rear quarter repaired? If so, do you have the repair invoice?
        4. Has the car ever been involved in an insurance claim?
        5. Are you the first owner, or was the car previously registered to a company/fleet?

        ---

        ## Estimated additional costs

        | Item | Estimated cost |
        |------|---------------|
        | Hybrid battery health check | ~200 PLN |
        | Bodywork inspection | ~150 PLN |
        | 4-wheel alignment | 150–300 PLN |
        | Tyre replacement (if needed) | 1,200–2,000 PLN |
        | **Total (worst case)** | **~2,650 PLN** |

        ---

        *AutoVerdict provides AI-assisted preliminary screening only. It does not replace professional
        inspection, vehicle history verification, or independent expert advice.*
        """;

    public async Task<string> ExecuteAsync(
        CarCheckRequestedMessage message,
        CancellationToken cancellationToken = default)
    {
        var delaySeconds = Rng.Next(5, 21);
        logger.LogInformation(
            "[TEST MODE] Fake pipeline started for check {CheckId}. Simulating {Delay}s of work.",
            message.CheckId, delaySeconds);

        await Task.Delay(TimeSpan.FromSeconds(delaySeconds), cancellationToken);

        var key = $"{message.CheckId}/{AnalysisFileName}";
        var bytes = Encoding.UTF8.GetBytes(FakeReport);
        await using var stream = new MemoryStream(bytes);
        await storage.UploadAsync(key, stream, "text/markdown; charset=utf-8", cancellationToken);

        logger.LogInformation(
            "[TEST MODE] Fake report saved to {Key} for check {CheckId}.",
            key, message.CheckId);

        return key;
    }
}
