apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: autoverdict
    user: autoverdict
    secureJsonData:
      password: autoverdict
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
    editable: true
